# target directory
output_dir: /lustre06/project/6004736/alvann/from_narval/DEV/test-scCoAnnotate-dev/out/

references: 'Braindex'
marker_genes: 'PDGFRA OLIG2 PTPRC'

# path to reference to train classifiers on (cell x gene raw counts)
training_reference: /lustre06/project/6004736/alvann/from_narval/DEV/reference-dev/Braindex_20210710/ref/expression.csv

# path to annotations for the reference (csv file with cellname and label headers)
reference_annotations: /lustre06/project/6004736/alvann/from_narval/DEV/reference-dev/Braindex_20210710/ref/labels.csv

# path to query datasets (cell x gene raw counts)
query_datasets:
      - /lustre06/project/6004736/alvann/from_narval/DEV/reference-dev/Braindex_20210710/samples/ct_p3/expression.csv
      - /lustre06/project/6004736/alvann/from_narval/DEV/reference-dev/Braindex_20210710/samples/ct_p0/expression.csv

# step to check if some genes are kept in the common gene space between ref and query
check_genes: False
genes_required: Null

# convert mouse genes of reference to human genes
convert_ref_mm_to_hg: False

# classifiers to run
tools_to_run:
      - scPred
      - SingleR
      - scClassify
      - SciBet
      - singleCellNet
      - scHPL 
      - SVMlinear
      - scLearn
      - Correlation

consensus_tools:
      - all 

# benchmark tools on reference
benchmark:
  n_folds: 3

