# Example config for scCoAnnotate annotation and benchmarking workflow 

# target directory 
output_dir: <path to annotation output>
output_dir_benchmark: <path to benchmark output>

# path to reference to train classifiers on (cell x gene raw counts)
references: 
      reference1:
            expression: <patht to expression.csv>0
            labels: <patht to labels.csv>
            ontology:
              ontology_path: <patht to ontology.csv>0
              ontology_column: <ontology_column to use>
            downsample:
                  value: 500 
                  stratified: True
            min_cells_per_cluster: 100
            convert_ref_mm_to_hg: False
      reference2:
            expression: <patht to expression.csv>
            labels: <patht to labels.csv>
            
# path to query datasets (cell x gene raw counts)
query_datasets:
      sample1: <patht to expression.csv>
      sample2: <patht to expression.csv>

# classifiers to run
tools_to_run:
      - scPred
      - SingleR
      - scClassify
      - SciBet
      - singleCellNet
      - scHPL
      - SVMlinear
      - Correlation
      - scLearn
      - ACTINN
      - scID
      - scAnnotate
      - scNym
      - CellTypist

consensus:
  tools: 
    - 'all'
  type:
    majority:
      min_agree: [5,6]
    CAWPE:
      mode: ['CAWPE_T','CAWPE_CT']
      alpha: [2,3,4]      
# Benchmark parameters 
benchmark:
  n_folds: 5 

