
#--- PREPROCESS ------

# convert gene symbols in reference from mouse to human 
convert_ref_mm_to_hg: False

# filter small clusters in reference 
min_cells_per_cluster: 0

downsample:
  value: 0
  stratified: False
  
#--- CONSENSUS -------

# specify consensus tools to include, either 'all' ot list of tool names
consensus_tools:
      - 'all'

# specify consensus type, either 'majority' or numeric value 
consensus_type: 'majority'

# alpha value for CAWPE calculation 
alpha: 4

#--- NOTEBOOKS -------

# genes of interest
# space separated string: "PDGFRA MOG GFAP RBFOX1"
marker_genes: ""

#---- TOOLS ----------
SingleR:
  threads: 1 

Correlation:
  threads: 1 

scPred:
  threads: 1
  classifier: 'svmRadial'  

scClassify:
  threads: 1 
  topN: 50 
  weightsCal: False 
  hopach_kmax: 5 
  algorithm: "WKNN"
  similarity: "pearson"
  prob_threshold: 0.7
  cor_threshold_static: 0.5
  cor_threshold_high: 0.7

SciBet:
  threads: 1

singleCellNet:
  threads: 1
  nTrees: 500 

scHPL:
  threads: 1
  classifier: 'svm'
  dimred: 'False'
  threshold: 0.5

SVMlinear:
  threads: 1
  threshold: 0
  classifier: 'SVMlinear'

SVC:
  threads: 1
  classifier: 'rbf'
  threshold: 0.5

ACTINN:
  threads: 1

scLearn:
  threads: 1
  bootstrap_times: 10

scID:
  threads: 1
  estimate_weights_from_target: False
  logFC: 0.5

scAnnotate:
  threads: 1
  threshold: 0.5

scNym:
  threads: 1
  threshold: 0.5

CellTypist:
  threads: 1 
  feature_selection: 'True'
  majority_voting: 'True'
  threshold: 0.5
#-----------------
